baseurl = "https://www.lacritica.ar/"
languageCode = "en-us"
languageLang = "en"
title = "La Crítica"
theme = "hugo-xmag"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
#disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/batalla1.jpeg"]
description = "La Crítica del Derecho"
social_image = "/img/batalla1.jpeg"
